# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'all', 'chrome-devtools://*')

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'all', 'devtools://*')

# Value to send in the `Accept-Language` header. Note that the value
# read from JavaScript is always the global value.
# Type: String
config.set('content.headers.accept_language', '', 'https://matchmaker.krunker.io/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{upstream_browser_version_short}`: The
# corresponding Safari/Chrome   version, but only with its major
# version. * `{qutebrowser_version}`: The currently running qutebrowser
# version.  The default value is equal to the default user agent of
# QtWebKit/QtWebEngine, but with the `QtWebEngine/...` part removed for
# increased compatibility.  Note that the value read from JavaScript is
# always the global value.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:136.0) Gecko/20100101 Firefox/136.0', 'https://accounts.google.com/*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'chrome-devtools://*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'devtools://*')

# Allow JavaScript to read from or write to the clipboard. With
# QtWebEngine, writing the clipboard as response to a user interaction
# is always allowed. On Qt < 6.8, the `ask` setting is equivalent to
# `none` and permission needs to be granted manually via this setting.
# Type: JSClipboardPermission
# Valid values:
#   - none: Disable access to clipboard.
#   - access: Allow reading from and writing to the clipboard.
#   - access-paste: Allow accessing the clipboard and pasting clipboard content.
#   - ask: Prompt when requested (grants 'access-paste' permission).
c.content.javascript.clipboard = 'access'

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome-devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Allow locally loaded documents to access remote URLs.
# Type: Bool
config.set('content.local_content_can_access_remote_urls', True, 'file:///Users/zen/Library/Application%20Support/qutebrowser/userscripts/*')

# Allow locally loaded documents to access other local URLs.
# Type: Bool
config.set('content.local_content_can_access_file_urls', False, 'file:///Users/zen/Library/Application%20Support/qutebrowser/userscripts/*')

# Allow websites to show notifications.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.notifications.enabled', False, 'https://www.youtube.com')

# Proxy to use. In addition to the listed values, you can use a
# `socks://...` or `http://...` URL. Note that with QtWebEngine, it will
# take a couple of seconds until the change is applied, if this value is
# changed at runtime. Authentication for SOCKS proxies isn't supported
# due to Chromium limitations.
# Type: Proxy
# Valid values:
#   - system: Use the system wide proxy.
#   - none: Don't use any proxy
c.content.proxy = 'system'

# When to show the statusbar.
# Type: String
# Valid values:
#   - always: Always show the statusbar.
#   - never: Always hide the statusbar.
#   - in-mode: Show the statusbar when in modes other than normal mode.
c.statusbar.show = 'in-mode'

# Padding (in pixels) for the statusbar.
# Type: Padding
c.statusbar.padding = {'bottom': 1, 'left': 6, 'right': 6, 'top': 1}

# How to behave when the last tab is closed. If the
# `tabs.tabs_are_windows` setting is set, this is ignored and the
# behavior is always identical to the `close` value.
# Type: String
# Valid values:
#   - ignore: Don't do anything.
#   - blank: Load a blank page.
#   - startpage: Load the start page.
#   - default-page: Load the default page.
#   - close: Close the window.
c.tabs.last_close = 'close'

# Padding (in pixels) around text for tabs.
# Type: Padding
c.tabs.padding = {'bottom': 5, 'left': 5, 'right': 5, 'top': 5}

# Position of the tab bar.
# Type: Position
# Valid values:
#   - top
#   - bottom
#   - left
#   - right
c.tabs.position = 'left'

# When to show the tab bar.
# Type: String
# Valid values:
#   - always: Always show the tab bar.
#   - never: Always hide the tab bar.
#   - multiple: Hide the tab bar if only one tab is open.
#   - switching: Show the tab bar when switching tabs.
c.tabs.show = 'never'

# Width (in pixels or as percentage of the window) of the tab bar if
# it's vertical.
# Type: PercOrInt
c.tabs.width = 300

# Hide the window decoration.  This setting requires a restart on
# Wayland.
# Type: Bool
c.window.hide_decoration = False

# Format to use for the window title. The same placeholders like for
# `tabs.title.format` are defined.
# Type: FormatString
c.window.title_format = '{perc}{current_url}{title_sep}{current_title}'

# Set the main window background to transparent.  This allows having a
# transparent tab- or statusbar (might require a compositor such as
# picom). However, it breaks some functionality such as dmenu embedding
# via its `-w` option. On some systems, it was additionally reported
# that main window transparency negatively affects performance.  Note
# this setting only affects windows opened after setting it.
# Type: Bool
c.window.transparent = True

# Default zoom level.
# Type: Perc
c.zoom.default = '100%'

# Number of zoom increments to divide the mouse wheel movements to.
# Type: Int
c.zoom.mouse_divider = 512

# Value to use for `prefers-color-scheme:` for websites. The "light"
# value is only available with QtWebEngine 5.15.2+. On older versions,
# it is the same as "auto". The "auto" value is broken on QtWebEngine
# 5.15.2 due to a Qt bug. There, it will fall back to "light"
# unconditionally.
# Type: String
# Valid values:
#   - auto: Use the system-wide color scheme setting.
#   - light: Force a light theme.
#   - dark: Force a dark theme.
c.colors.webpage.preferred_color_scheme = 'dark'
# base16-qutebrowser (https://github.com/theova/base16-qutebrowser)
# Scheme name: Gruvbox dark, soft
# Scheme author: Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
# Template author: theova
# Commentary: Tinted Theming: (https://github.com/tinted-theming)

base00 = "#32302f"
base01 = "#3c3836"
base02 = "#504945"
base03 = "#665c54"
base04 = "#bdae93"
base05 = "#d5c4a1"
base06 = "#ebdbb2"
base07 = "#fbf1c7"
base08 = "#fb4934"
base09 = "#fe8019"
base0A = "#fabd2f"
base0B = "#b8bb26"
base0C = "#8ec07c"
base0D = "#83a598"
base0E = "#d3869b"
base0F = "#d65d0e"

# set qutebrowser colors

# Text color of the completion widget. May be a single color to use for
# all columns or a list of three colors, one for each column.
c.colors.completion.fg = base05

# Background color of the completion widget for odd rows.
c.colors.completion.odd.bg = base01

# Background color of the completion widget for even rows.
c.colors.completion.even.bg = base00

# Foreground color of completion widget category headers.
c.colors.completion.category.fg = base0A

# Background color of the completion widget category headers.
c.colors.completion.category.bg = base00

# Top border color of the completion widget category headers.
c.colors.completion.category.border.top = base00

# Bottom border color of the completion widget category headers.
c.colors.completion.category.border.bottom = base00

# Foreground color of the selected completion item.
c.colors.completion.item.selected.fg = base05

# Background color of the selected completion item.
c.colors.completion.item.selected.bg = base02

# Top border color of the selected completion item.
c.colors.completion.item.selected.border.top = base02

# Bottom border color of the selected completion item.
c.colors.completion.item.selected.border.bottom = base02

# Foreground color of the matched text in the selected completion item.
c.colors.completion.item.selected.match.fg = base0B

# Foreground color of the matched text in the completion.
c.colors.completion.match.fg = base0B

# Color of the scrollbar handle in the completion view.
c.colors.completion.scrollbar.fg = base05

# Color of the scrollbar in the completion view.
c.colors.completion.scrollbar.bg = base00

# Background color of disabled items in the context menu.
c.colors.contextmenu.disabled.bg = base01

# Foreground color of disabled items in the context menu.
c.colors.contextmenu.disabled.fg = base04

# Background color of the context menu. If set to null, the Qt default is used.
c.colors.contextmenu.menu.bg = base00

# Foreground color of the context menu. If set to null, the Qt default is used.
c.colors.contextmenu.menu.fg =  base05

# Background color of the context menu’s selected item. If set to null, the Qt default is used.
c.colors.contextmenu.selected.bg = base02

#Foreground color of the context menu’s selected item. If set to null, the Qt default is used.
c.colors.contextmenu.selected.fg = base05

# Background color for the download bar.
c.colors.downloads.bar.bg = base00

# Color gradient start for download text.
c.colors.downloads.start.fg = base00

# Color gradient start for download backgrounds.
c.colors.downloads.start.bg = base0D

# Color gradient end for download text.
c.colors.downloads.stop.fg = base00

# Color gradient stop for download backgrounds.
c.colors.downloads.stop.bg = base0C

# Foreground color for downloads with errors.
c.colors.downloads.error.fg = base08

# Font color for hints.
c.colors.hints.fg = base00

# Background color for hints. Note that you can use a `rgba(...)` value
# for transparency.
c.colors.hints.bg = base0A

# Font color for the matched part of hints.
c.colors.hints.match.fg = base05

# Text color for the keyhint widget.
c.colors.keyhint.fg = base05

# Highlight color for keys to complete the current keychain.
c.colors.keyhint.suffix.fg = base05

# Background color of the keyhint widget.
c.colors.keyhint.bg = base00

# Foreground color of an error message.
c.colors.messages.error.fg = base00

# Background color of an error message.
c.colors.messages.error.bg = base08

# Border color of an error message.
c.colors.messages.error.border = base08

# Foreground color of a warning message.
c.colors.messages.warning.fg = base00

# Background color of a warning message.
c.colors.messages.warning.bg = base0E

# Border color of a warning message.
c.colors.messages.warning.border = base0E

# Foreground color of an info message.
c.colors.messages.info.fg = base05

# Background color of an info message.
c.colors.messages.info.bg = base00

# Border color of an info message.
c.colors.messages.info.border = base00

# Foreground color for prompts.
c.colors.prompts.fg = base05

# Border used around UI elements in prompts.
c.colors.prompts.border = base00

# Background color for prompts.
c.colors.prompts.bg = base00

# Background color for the selected item in filename prompts.
c.colors.prompts.selected.bg = base02

# Foreground color for the selected item in filename prompts.
c.colors.prompts.selected.fg = base05

# Foreground color of the statusbar.
c.colors.statusbar.normal.fg = base0B

# Background color of the statusbar.
c.colors.statusbar.normal.bg = base00

# Foreground color of the statusbar in insert mode.
c.colors.statusbar.insert.fg = base00

# Background color of the statusbar in insert mode.
c.colors.statusbar.insert.bg = base0D

# Foreground color of the statusbar in passthrough mode.
c.colors.statusbar.passthrough.fg = base00

# Background color of the statusbar in passthrough mode.
c.colors.statusbar.passthrough.bg = base0C

# Foreground color of the statusbar in private browsing mode.
c.colors.statusbar.private.fg = base00

# Background color of the statusbar in private browsing mode.
c.colors.statusbar.private.bg = base01

# Foreground color of the statusbar in command mode.
c.colors.statusbar.command.fg = base05

# Background color of the statusbar in command mode.
c.colors.statusbar.command.bg = base00

# Foreground color of the statusbar in private browsing + command mode.
c.colors.statusbar.command.private.fg = base05

# Background color of the statusbar in private browsing + command mode.
c.colors.statusbar.command.private.bg = base00

# Foreground color of the statusbar in caret mode.
c.colors.statusbar.caret.fg = base00

# Background color of the statusbar in caret mode.
c.colors.statusbar.caret.bg = base0E

# Foreground color of the statusbar in caret mode with a selection.
c.colors.statusbar.caret.selection.fg = base00

# Background color of the statusbar in caret mode with a selection.
c.colors.statusbar.caret.selection.bg = base0D

# Background color of the progress bar.
c.colors.statusbar.progress.bg = base0D

# Default foreground color of the URL in the statusbar.
c.colors.statusbar.url.fg = base05

# Foreground color of the URL in the statusbar on error.
c.colors.statusbar.url.error.fg = base08

# Foreground color of the URL in the statusbar for hovered links.
c.colors.statusbar.url.hover.fg = base05

# Foreground color of the URL in the statusbar on successful load
# (http).
c.colors.statusbar.url.success.http.fg = base0C

# Foreground color of the URL in the statusbar on successful load
# (https).
c.colors.statusbar.url.success.https.fg = base0B

# Foreground color of the URL in the statusbar when there's a warning.
c.colors.statusbar.url.warn.fg = base0E

# Background color of the tab bar.
c.colors.tabs.bar.bg = base00

# Color gradient start for the tab indicator.
c.colors.tabs.indicator.start = base0D

# Color gradient end for the tab indicator.
c.colors.tabs.indicator.stop = base0C

# Color for the tab indicator on errors.
c.colors.tabs.indicator.error = base08

# Foreground color of unselected odd tabs.
c.colors.tabs.odd.fg = base05

# Background color of unselected odd tabs.
c.colors.tabs.odd.bg = base01

# Foreground color of unselected even tabs.
c.colors.tabs.even.fg = base05

# Background color of unselected even tabs.
c.colors.tabs.even.bg = base00

# Background color of pinned unselected even tabs.
c.colors.tabs.pinned.even.bg = base0C

# Foreground color of pinned unselected even tabs.
c.colors.tabs.pinned.even.fg = base07

# Background color of pinned unselected odd tabs.
c.colors.tabs.pinned.odd.bg = base0B

# Foreground color of pinned unselected odd tabs.
c.colors.tabs.pinned.odd.fg = base07

# Background color of pinned selected even tabs.
c.colors.tabs.pinned.selected.even.bg = base02

# Foreground color of pinned selected even tabs.
c.colors.tabs.pinned.selected.even.fg = base05

# Background color of pinned selected odd tabs.
c.colors.tabs.pinned.selected.odd.bg = base02

# Foreground color of pinned selected odd tabs.
c.colors.tabs.pinned.selected.odd.fg = base05

# Foreground color of selected odd tabs.
c.colors.tabs.selected.odd.fg = base05

# Background color of selected odd tabs.
c.colors.tabs.selected.odd.bg = base02

# Foreground color of selected even tabs.
c.colors.tabs.selected.even.fg = base05

# Background color of selected even tabs.
c.colors.tabs.selected.even.bg = base02

# Background color for webpages if unset (or empty to use the theme's
# color).
c.colors.webpage.bg = base00

c.colors.webpage.darkmode.enabled = True

c.editor.command = ["kitty","--wait-for-single-instance-window-close", "-T", "auxiliary text edit", "nvim", "{file}", "+call cursor({line}, {column})"]

c.url.searchengines = {
    'DEFAULT': "https://duckduckgo.com/?q={}",
    "ytn": "https://youtrack.rtlq.ru/issue/{}/", # по номеру
    "yt": "https://youtrack.rtlq.ru/issues?q={}", # поиск
    "gl": "https://gitlab.clabs.net/crona/kkrm/-/merge_requests?scope=all&state=all&search={}",
    "gln": "https://gitlab.clabs.net/crona/kkrm/-/merge_requests/{}/",
}

# BINDS

config.bind("td", "config-cycle colors.webpage.darkmode.enabled true false")
config.bind("tt", "config-cycle tabs.show always never")
config.bind("ее", "config-cycle tabs.show always never") # russian

config.bind("gj", "scroll-px 0 25")
config.bind("gk", "scroll-px 0 -25")

config.bind('<z><l>', 'spawn --userscript qute-pass.py')
config.bind('<z><u><l>', 'spawn --userscript qute-pass.py --username-only')
config.bind('<z><p><l>', 'spawn --userscript qute-pass.py --password-only')
config.bind('<z><o><l>', 'spawn --userscript qute-pass.py --otp-only')



# Russian key binds

# mode="caret"
config.bind("П", "move-to-end-of-document", mode="caret")
config.bind("Р", "scroll left", mode="caret")
config.bind("О", "scroll down", mode="caret")
config.bind("Л", "scroll up", mode="caret")
config.bind("Д", "scroll right", mode="caret")
config.bind("М", "selection-toggle --line", mode="caret")
config.bind("Н", "yank selection -s", mode="caret")
config.bind("х", "move-to-start-of-prev-block", mode="caret")
config.bind("ъ", "move-to-start-of-next-block", mode="caret")
config.bind("и", "move-to-prev-word", mode="caret")
config.bind("с", "mode-enter normal", mode="caret")
config.bind("е", "move-to-end-of-word", mode="caret")
config.bind("пп", "move-to-start-of-document", mode="caret")
config.bind("р", "move-to-prev-char", mode="caret")
config.bind("о", "move-to-next-line", mode="caret")
config.bind("л", "move-to-prev-line", mode="caret")
config.bind("д", "move-to-next-char", mode="caret")
config.bind("щ", "selection-reverse", mode="caret")
config.bind("м", "selection-toggle", mode="caret")
config.bind("ц", "move-to-next-word", mode="caret")
config.bind("н", "yank selection", mode="caret")

# mode="command"
config.bind("<Alt-И>", "rl-backward-word", mode="command")
config.bind("<Alt-В>", "rl-kill-word", mode="command")
config.bind("<Alt-А>", "rl-forward-word", mode="command")
config.bind("<Ctrl-,>", "rl-delete-char", mode="command")
config.bind("<Ctrl-Ф>", "rl-beginning-of-line", mode="command")
config.bind("<Ctrl-И>", "rl-backward-char", mode="command")
config.bind("<Ctrl-С>", "completion-item-yank", mode="command")
config.bind("<Ctrl-В>", "completion-item-del", mode="command")
config.bind("<Ctrl-У>", "rl-end-of-line", mode="command")
config.bind("<Ctrl-А>", "rl-forward-char", mode="command")
config.bind("<Ctrl-Р>", "rl-backward-delete-char", mode="command")
config.bind("<Ctrl-Л>", "rl-kill-line", mode="command")
config.bind("<Ctrl-Т>", "command-history-next", mode="command")
config.bind("<Ctrl-З>", "command-history-prev", mode="command")
config.bind("<Ctrl-Shift-С>", "completion-item-yank --sel", mode="command")
config.bind("<Ctrl-Shift-Ц>", "rl-filename-rubout", mode="command")
config.bind("<Ctrl-Г>", "rl-unix-line-discard", mode="command")
config.bind("<Ctrl-Ц>", 'rl-rubout " "', mode="command")
config.bind("<Ctrl-Н>", "rl-yank", mode="command")

# mode="hint"
config.bind("<Ctrl-И>", "hint all tab-bg", mode="hint")
config.bind("<Ctrl-А>", "hint links", mode="hint")
config.bind("<Ctrl-К>", "hint --rapid links tab-bg", mode="hint")

# mode="insert"
config.bind("<Ctrl-У>", "edit-text", mode="insert")

# mode="normal"
config.bind("э", "mode-enter jump_mark", mode="normal")
config.bind("ю", "repeat-command", mode="normal")
config.bind(".", "set-cmd-text /", mode="normal")
config.bind("Ж", "set-cmd-text :", mode="normal")
config.bind("жШ", "hint images tab", mode="normal")
config.bind("жЩ", "hint links fill :open -t -r {hint-url}", mode="normal")
config.bind("жК", "hint --rapid links window", mode="normal")
config.bind("жН", "hint links yank-primary", mode="normal")
config.bind("жи", "hint all tab-bg", mode="normal")
config.bind("жв", "hint links download", mode="normal")
config.bind("жа", "hint all tab-fg", mode="normal")
config.bind("жр", "hint all hover", mode="normal")
config.bind("жш", "hint images", mode="normal")
config.bind("жщ", "hint links fill :open {hint-url}", mode="normal")
config.bind("жк", "hint --rapid links tab-bg", mode="normal")
config.bind("же", "hint inputs", mode="normal")
config.bind("жн", "hint links yank", mode="normal")
config.bind("<Alt-ь>", "tab-mute", mode="normal")
config.bind("<Ctrl-Ф>", "navigate increment", mode="normal")
config.bind("<Ctrl-Alt-з>", "print", mode="normal")
config.bind("<Ctrl-И>", "scroll-page 0 -1", mode="normal")
config.bind("<Ctrl-В>", "scroll-page 0 0.5", mode="normal")
config.bind("<Ctrl-А>", "scroll-page 0 1", mode="normal")
config.bind("<Ctrl-Т>", "open -w", mode="normal")
config.bind("<Ctrl-Й>", "quit", mode="normal")
config.bind("<Ctrl-Shift-Т>", "open -p", mode="normal")
config.bind("<Ctrl-Shift-Е>", "undo", mode="normal")
config.bind("<Ctrl-Shift-Ц>", "close", mode="normal")
config.bind("<Ctrl-Е>", "open -t", mode="normal")
config.bind("<Ctrl-Г>", "scroll-page 0 -0.5", mode="normal")
config.bind("<Ctrl-М>", "mode-enter passthrough", mode="normal")
config.bind("<Ctrl-Ц>", "tab-close", mode="normal")
config.bind("<Ctrl-Ч>", "navigate decrement", mode="normal")
config.bind("<Ctrl-:>", "tab-focus last", mode="normal")
config.bind("<Ctrl-р>", "home", mode="normal")
config.bind("<Ctrl-з>", "tab-pin", mode="normal")
config.bind("<Ctrl-ы>", "stop", mode="normal")
config.bind(",", "set-cmd-text ?", mode="normal")
config.bind('"', "macro-run", mode="normal")
config.bind("И", "set-cmd-text -s :quickmark-load -t", mode="normal")
config.bind("В", "tab-close -o", mode="normal")
config.bind("А", "hint all tab", mode="normal")
config.bind("П", "scroll-to-perc", mode="normal")
config.bind("Р", "back", mode="normal")
config.bind("О", "tab-next", mode="normal")
config.bind("Л", "tab-prev", mode="normal")
config.bind("Д", "forward", mode="normal")
config.bind("Ь", "bookmark-add", mode="normal")
config.bind("Т", "search-prev", mode="normal")
config.bind("Щ", "set-cmd-text -s :open -t", mode="normal")
config.bind("ЗЗ", "open -t -- {primary}", mode="normal")
config.bind("Зз", "open -t -- {clipboard}", mode="normal")
config.bind("К", "reload -f", mode="normal")
config.bind("Ыи", "bookmark-list --jump", mode="normal")
config.bind("Ыр", "history", mode="normal")
config.bind("Ый", "bookmark-list", mode="normal")
config.bind("Ыы", "set", mode="normal")
config.bind("Е", "set-cmd-text -sr :tab-focus", mode="normal")
config.bind("Г", "undo -w", mode="normal")
config.bind("М", "mode-enter caret ;; selection-toggle --line", mode="normal")
config.bind("ЯЙ", "quit", mode="normal")
config.bind("ЯЯ", "quit --save", mode="normal")
config.bind("хх", "navigate prev", mode="normal")
config.bind("ъъ", "navigate next", mode="normal")
config.bind("ё", "mode-enter set_mark", mode="normal")
config.bind("фв", "download-cancel", mode="normal")
config.bind("и", "set-cmd-text -s :quickmark-load", mode="normal")
config.bind("св", "download-clear", mode="normal")
config.bind("сщ", "tab-only", mode="normal")
config.bind("в", "tab-close", mode="normal")
config.bind("а", "hint", mode="normal")
config.bind("п;", "tab-focus -1", mode="normal")
config.bind("п0", "tab-focus 1", mode="normal")
config.bind("пИ", "set-cmd-text -s :bookmark-load -t", mode="normal")
config.bind("пС", "tab-clone", mode="normal")
config.bind("пВ", "tab-give", mode="normal")
config.bind("пО", "tab-move +", mode="normal")
config.bind("пЛ", "tab-move -", mode="normal")
config.bind("пЩ", "set-cmd-text :open -t -r {url:pretty}", mode="normal")
config.bind("пГ", "navigate up -t", mode="normal")
config.bind("п:", "tab-focus 1", mode="normal")
config.bind("пф", "open -t", mode="normal")
config.bind("пи", "set-cmd-text -s :bookmark-load", mode="normal")
config.bind("пв", "download", mode="normal")
config.bind("па", "view-source", mode="normal")
config.bind("пп", "scroll-to-perc 0", mode="normal")
config.bind("пш", "hint inputs --first", mode="normal")
config.bind("пь", "tab-move", mode="normal")
config.bind("пщ", "set-cmd-text :open {url:pretty}", mode="normal")
config.bind("пе", "set-cmd-text -s :tab-select", mode="normal")
config.bind("пг", "navigate up", mode="normal")
config.bind("р", "scroll left", mode="normal")
config.bind("ш", "mode-enter insert", mode="normal")
config.bind("о", "scroll down", mode="normal")
config.bind("л", "scroll up", mode="normal")
config.bind("д", "scroll right", mode="normal")
config.bind("ь", "quickmark-save", mode="normal")
config.bind("т", "search-next", mode="normal")
config.bind("щ", "set-cmd-text -s :open", mode="normal")
config.bind("зЗ", "open -- {primary}", mode="normal")
config.bind("зз", "open -- {clipboard}", mode="normal")
config.bind("й", "macro-record", mode="normal")
config.bind("к", "reload", mode="normal")
config.bind("ыа", "save", mode="normal")
config.bind("ыл", "set-cmd-text -s :bind", mode="normal")
config.bind("ыд", "set-cmd-text -s :set -t", mode="normal")
config.bind("ыы", "set-cmd-text -s :set", mode="normal")
config.bind(
    "еСР",
    "config-cycle -p -u *://*.{url:host}/* content.cookies.accept all no-3rdparty never ;; reload",
    mode="normal",
)
config.bind(
    "еСр",
    "config-cycle -p -u *://{url:host}/* content.cookies.accept all no-3rdparty never ;; reload",
    mode="normal",
)
config.bind(
    "еСг",
    "config-cycle -p -u {url} content.cookies.accept all no-3rdparty never ;; reload",
    mode="normal",
)
config.bind(
    "еШР",
    "config-cycle -p -u *://*.{url:host}/* content.images ;; reload",
    mode="normal",
)
config.bind(
    "еШр", "config-cycle -p -u *://{url:host}/* content.images ;; reload", mode="normal"
)
config.bind("еШг", "config-cycle -p -u {url} content.images ;; reload", mode="normal")
config.bind(
    "еЗР",
    "config-cycle -p -u *://*.{url:host}/* content.plugins ;; reload",
    mode="normal",
)
config.bind(
    "еЗр",
    "config-cycle -p -u *://{url:host}/* content.plugins ;; reload",
    mode="normal",
)
config.bind("еЗг", "config-cycle -p -u {url} content.plugins ;; reload", mode="normal")
config.bind(
    "еЫР",
    "config-cycle -p -u *://*.{url:host}/* content.javascript.enabled ;; reload",
    mode="normal",
)
config.bind(
    "еЫр",
    "config-cycle -p -u *://{url:host}/* content.javascript.enabled ;; reload",
    mode="normal",
)
config.bind(
    "еЫг",
    "config-cycle -p -u {url} content.javascript.enabled ;; reload",
    mode="normal",
)
config.bind(
    "есР",
    "config-cycle -p -t -u *://*.{url:host}/* content.cookies.accept all no-3rdparty never ;; reload",
    mode="normal",
)
config.bind(
    "еср",
    "config-cycle -p -t -u *://{url:host}/* content.cookies.accept all no-3rdparty never ;; reload",
    mode="normal",
)
config.bind(
    "есг",
    "config-cycle -p -t -u {url} content.cookies.accept all no-3rdparty never ;; reload",
    mode="normal",
)
config.bind("ер", "back -t", mode="normal")
config.bind(
    "ешР",
    "config-cycle -p -t -u *://*.{url:host}/* content.images ;; reload",
    mode="normal",
)
config.bind(
    "ешр",
    "config-cycle -p -t -u *://{url:host}/* content.images ;; reload",
    mode="normal",
)
config.bind(
    "ешг", "config-cycle -p -t -u {url} content.images ;; reload", mode="normal"
)
config.bind("ед", "forward -t", mode="normal")
config.bind(
    "езР",
    "config-cycle -p -t -u *://*.{url:host}/* content.plugins ;; reload",
    mode="normal",
)
config.bind(
    "езр",
    "config-cycle -p -t -u *://{url:host}/* content.plugins ;; reload",
    mode="normal",
)
config.bind(
    "езг", "config-cycle -p -t -u {url} content.plugins ;; reload", mode="normal"
)
config.bind(
    "еыР",
    "config-cycle -p -t -u *://*.{url:host}/* content.javascript.enabled ;; reload",
    mode="normal",
)
config.bind(
    "еыр",
    "config-cycle -p -t -u *://{url:host}/* content.javascript.enabled ;; reload",
    mode="normal",
)
config.bind(
    "еыг",
    "config-cycle -p -t -u {url} content.javascript.enabled ;; reload",
    mode="normal",
)
config.bind("г", "undo", mode="normal")
config.bind("м", "mode-enter caret", mode="normal")
config.bind("цИ", "set-cmd-text -s :bookmark-load -w", mode="normal")
config.bind("цШа", "devtools-focus", mode="normal")
config.bind("цШр", "devtools left", mode="normal")
config.bind("цШо", "devtools bottom", mode="normal")
config.bind("цШл", "devtools top", mode="normal")
config.bind("цШд", "devtools right", mode="normal")
config.bind("цШц", "devtools window", mode="normal")
config.bind("цЩ", "set-cmd-text :open -w {url:pretty}", mode="normal")
config.bind("цЗ", "open -w -- {primary}", mode="normal")
config.bind("ци", "set-cmd-text -s :quickmark-load -w", mode="normal")
config.bind("ца", "hint all window", mode="normal")
config.bind("цр", "back -w", mode="normal")
config.bind("цш", "devtools", mode="normal")
config.bind("цд", "forward -w", mode="normal")
config.bind("цщ", "set-cmd-text -s :open -w", mode="normal")
config.bind("цз", "open -w -- {clipboard}", mode="normal")
config.bind("чЩ", "set-cmd-text :open -b -r {url:pretty}", mode="normal")
config.bind("чщ", "set-cmd-text -s :open -b", mode="normal")
config.bind("нВ", "yank domain -s", mode="normal")
config.bind("нЬ", "yank inline [{title}]({url}) -s", mode="normal")
config.bind("нЗ", "yank pretty-url -s", mode="normal")
config.bind("нЕ", "yank title -s", mode="normal")
config.bind("нН", "yank -s", mode="normal")
config.bind("нв", "yank domain", mode="normal")
config.bind("нь", "yank inline [{title}]({url})", mode="normal")
config.bind("нз", "yank pretty-url", mode="normal")
config.bind("не", "yank title", mode="normal")
config.bind("нн", "yank", mode="normal")
config.bind("ХХ", "navigate prev -t", mode="normal")
config.bind("ЪЪ", "navigate next -t", mode="normal")

# mode="prompt"
config.bind("<Alt-И>", "rl-backward-word"               , mode="prompt")
config.bind("<Alt-В>", "rl-kill-word"                   , mode="prompt")
config.bind("<Alt-А>", "rl-forward-word"                , mode="prompt")
config.bind("<Alt-Shift-Н>", "prompt-yank --sel"        , mode="prompt")
config.bind("<Alt-Н>", "prompt-yank"                    , mode="prompt")
config.bind("<Ctrl-,>", "rl-delete-char"                , mode="prompt")
config.bind("<Ctrl-Ф>", "rl-beginning-of-line"          , mode="prompt")
config.bind("<Ctrl-И>", "rl-backward-char"              , mode="prompt")
config.bind("<Ctrl-У>", "rl-end-of-line"                , mode="prompt")
config.bind("<Ctrl-А>", "rl-forward-char"               , mode="prompt")
config.bind("<Ctrl-Р>", "rl-backward-delete-char"       , mode="prompt")
config.bind("<Ctrl-Л>", "rl-kill-line"                  , mode="prompt")
config.bind("<Ctrl-З>", "prompt-open-download --pdfjs"  , mode="prompt")
config.bind("<Ctrl-Shift-Ц>", "rl-filename-rubout"      , mode="prompt")
config.bind("<Ctrl-Г>", "rl-unix-line-discard"          , mode="prompt")
config.bind("<Ctrl-Ц>", 'rl-rubout " "'                 , mode="prompt")
config.bind("<Ctrl-Ч>", "prompt-open-download"          , mode="prompt")
config.bind("<Ctrl-Н>", "rl-yank"                       , mode="prompt")

# mode="yesno"
config.bind("<Alt-Shift-Н>", "prompt-yank --sel"  , mode="yesno")
config.bind("<Alt-Н>", "prompt-yank"              , mode="yesno")
config.bind("Т", "prompt-accept --save no"        , mode="yesno")
config.bind("Н", "prompt-accept --save yes"       , mode="yesno")
config.bind("т", "prompt-accept no"               , mode="yesno")
config.bind("н", "prompt-accept yes"              , mode="yesno")

